server {
    listen 80;
    server_name risk-theory.bluehour.cloud;
    set $upstream http://risk-theory-web:3000;

    location / {
        proxy_pass $upstream;
        include /etc/nginx/proxy_params;
        proxy_set_header X-Forwarded-Proto $origin_scheme;
        proxy_read_timeout 120s;
        proxy_send_timeout 120s;
    }
}

server {
    listen 80;
    server_name api.risk-theory.bluehour.cloud;
    client_max_body_size 2m;
    set $upstream http://risk-theory-api:8000;

    location / {
        proxy_pass $upstream;
        include /etc/nginx/proxy_params;
        proxy_set_header X-Forwarded-Proto $origin_scheme;
        proxy_read_timeout 120s;
        proxy_send_timeout 120s;
    }
}
